In [8]:
import numpy as np

grid = [
    [0, 0, 0, 0, 7, 8, 0, 0, 2],
    [6, 0, 0, 1, 0, 0, 0, 0, 8],
    [1, 9, 8, 0, 4, 2, 0, 0, 7],
    [8, 5, 0, 0, 6, 0, 0, 2, 3],
    [4, 0, 0, 8, 0, 0, 7, 0, 1],
    [7, 0, 0, 0, 2, 4, 0, 5, 6],
    [9, 6, 1, 5, 0, 0, 0, 8, 4],
    [2, 8, 0, 0, 1, 9, 0, 0, 5],
    [3, 4, 5, 2, 0, 6, 0, 7, 9]
]

def possible(x, y, n, grid): #vérif si le n est possible et si il est présent dans la grille et dans les sous-grille
    for i in range(0, 9):
        if grid[x][i] == n:
            return False
    for i in range(0, 9):
        if grid[i][y] == n:
            return False
    x0 = (y // 3) * 3
    y0 = (x // 3) * 3
    for i in range(0, 3):
        for j in range(0, 3):
            if grid[y0+i][x0+j] == n:
                return False
    return True

def solve(grid): # récursivité, parcourt chaque cellule pour savoir si elle est vide et essaye des valeurs
    for x in range(0, 9):
        for y in range(0, 9):
            if grid[x][y] == 0:
                for n in range(1, 10):
                    if possible(x, y, n, grid):
                        grid[x][y] = n
                        solve(grid)
                        grid[x][y] = 0
                return
    print(np.matrix(grid))
    more = input('Autre solutions ? : ')
    if more.lower() == 'oui': #convertir la chaine de caractère dans une variable minuscule
        solve(grid)


solve(grid)


[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
Autre solutions ? : oui
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


KeyboardInterrupt: Interrupted by user